
FetchContent_Declare(
	rapidjson
	GIT_REPOSITORY https://github.com/Tencent/rapidjson
	GIT_TAG 24b5e7a
	SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/rapidjson"
)
set(RAPIDJSON_BUILD_DOC OFF CACHE BOOL "")
set(RAPIDJSON_BUILD_EXAMPLES OFF CACHE BOOL "")
set(RAPIDJSON_BUILD_TESTS OFF CACHE BOOL "")
set(RAPIDJSON_BUILD_CXX11 OFF CACHE BOOL "")
set(RAPIDJSON_BUILD_CXX17 ON CACHE BOOL "")
set(RAPIDJSON_BUILD_THIRDPARTY_GTEST OFF CACHE BOOL "")

FetchContent_MakeAvailable(rapidjson)